package bean;
// Generated 14/09/2023 10:07:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VeccVendaProduto generated by hbm2java
 */
@Entity
@Table(name="vecc_venda_produto"
    ,catalog="db_victor_cardoso"
)
public class VeccVendaProduto  implements java.io.Serializable {


     private int veccIdvendaProduto;
     private int veccProduto;
     private int veccVenda;
     private int veccQuantidade;
     private String veccValor;

    public VeccVendaProduto() {
    }

	
    public VeccVendaProduto(int veccIdvendaProduto, int veccProduto, int veccVenda) {
        this.veccIdvendaProduto = veccIdvendaProduto;
        this.veccProduto = veccProduto;
        this.veccVenda = veccVenda;
    }
    public VeccVendaProduto(int veccIdvendaProduto, int veccProduto, int veccVenda, int veccQuantidade, String veccValor) {
       this.veccIdvendaProduto = veccIdvendaProduto;
       this.veccProduto = veccProduto;
       this.veccVenda = veccVenda;
       this.veccQuantidade = veccQuantidade;
       this.veccValor = veccValor;
    }
   
     @Id 

    
    @Column(name="vecc_idvenda_produto", unique=true, nullable=false)
    public int getVeccIdvendaProduto() {
        return this.veccIdvendaProduto;
    }
    
    public void setVeccIdvendaProduto(int veccIdvendaProduto) {
        this.veccIdvendaProduto = veccIdvendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vecc_fk_produtos", nullable=false)
    public int getVeccProduto() {
        return this.veccProduto;
    }
    
    public void setVeccProduto(int veccProduto) {
        this.veccProduto = veccProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vecc_fk_venda", nullable=false)
    public int getVeccVenda() {
        return this.veccVenda;
    }
    
    public void setVeccVenda(int veccVenda) {
        this.veccVenda = veccVenda;
    }

    
    @Column(name="vecc_quantidade", length=45)
    public int getVeccQuantidade() {
        return this.veccQuantidade;
    }
    
    public void setVeccQuantidade(int veccQuantidade) {
        this.veccQuantidade = veccQuantidade;
    }

    
    @Column(name="vecc_valor", length=45)
    public String getVeccValor() {
        return this.veccValor;
    }
    
    public void setVeccValor(String veccValor) {
        this.veccValor = veccValor;
    }




}


